-----------  Obtener la lista de precios de todos los productos


SELECT ID_ITEM CONSECUTIVO, CODIGO_ITEM, DESCRIPCION, CONVERT(MONEY,PRECIO) PRECIO
FROM   INVENTARIOS ORDER BY 1 

-----------  Obtener la lista de productos cuya existencia en el inventario haya llegado al mínimo permitido (5 unidades)

SELECT ID_ITEM CONSECUTIVO, CODIGO_ITEM, DESCRIPCION, CANTIDAD_STOCK, STOCK_MINIMO
FROM   INVENTARIOS
WHERE  (CANTIDAD_STOCK <= STOCK_MINIMO)


-----------  Obtener una lista de clientes no mayores de 35 años que hayan realizado compras entre el 1 de febrero de 2000 y el 25 de mayo de 2000

DECLARE @FCH_INI DATE = '02/01/2000',@FCH_FNL DATE ='05/25/2000',@EDAD INT =35
SELECT	DISTINCT CLIENTES.ID_CLIENTE, CLIENTES.NUMERO_IDENTIFICACION, 
		CLIENTES.NOMBRE_COMPLETO, CLIENTES.FECHA_NACIMIENTO
FROM	CLIENTES INNER JOIN MOVIMIENTOS ON 
		CLIENTES.ID_CLIENTE = MOVIMIENTOS.ID_CLIENTE
WHERE	(MOVIMIENTOS.FECHA BETWEEN @FCH_INI AND @FCH_FNL) AND 
		(YEAR(DATEADD(YEAR, @EDAD, CLIENTES.FECHA_NACIMIENTO)) <= YEAR(GETDATE()))


-----------  Obtener el valor total vendido por cada producto en el año 2000


DECLARE @ANN INT = 2000
SELECT	INVENTARIOS.ID_ITEM, INVENTARIOS.CODIGO_ITEM, INVENTARIOS.DESCRIPCION, SUM(INVENTARIOS.PRECIO * DTB.CANTIDAD) AS TOTAL, @ANN AS FECHA
FROM    INVENTARIOS INNER JOIN
        (SELECT DETALLE_MOVIMIENTOS.ID_ITEM, DETALLE_MOVIMIENTOS.CANTIDAD
		 FROM      MOVIMIENTOS INNER JOIN
		 DETALLE_MOVIMIENTOS ON MOVIMIENTOS.ID_MOVIMIENTO = DETALLE_MOVIMIENTOS.ID_MOVIMIENTO
         WHERE   (YEAR(MOVIMIENTOS.FECHA) = @ANN)) AS DTB ON INVENTARIOS.ID_ITEM = DTB.ID_ITEM
GROUP BY INVENTARIOS.ID_ITEM, INVENTARIOS.CODIGO_ITEM, INVENTARIOS.DESCRIPCION


-----------  Obtener la última fecha de compra de un cliente y según su frecuencia de compra estimar en qué fecha podría volver a comprar


DECLARE @ANN INT = 2000
SELECT		@ANN AS FECHA, MOVIMIENTOS.ID_CLIENTE, CLIENTES.NUMERO_IDENTIFICACION, CLIENTES.NOMBRE_COMPLETO,MAX(MOVIMIENTOS.FECHA) AS [FECHA RECIENTE], 
			CASE DATEDIFF(DAY, MIN(FECHA), MAX(FECHA)) WHEN 0 THEN DATEADD(DAY, 1,MAX(FECHA)) ELSE DATEADD(DAY, DATEDIFF(DAY, MIN(FECHA), MAX(FECHA)) / COUNT(FECHA), MAX(FECHA)) END AS [FECHA PROMEDIO], AVG(MOVIMIENTOS.TOTAL) AS [VALOR PROMEDIO]
FROM		MOVIMIENTOS INNER JOIN CLIENTES ON MOVIMIENTOS.ID_CLIENTE = CLIENTES.ID_CLIENTE
GROUP BY	MOVIMIENTOS.ID_CLIENTE, CLIENTES.NUMERO_IDENTIFICACION, CLIENTES.NOMBRE_COMPLETO



-----------  
